# Generated by Django 2.0.7 on 2018-08-05 08:10

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否发表')),
                ('body', mdeditor.fields.MDTextField(verbose_name='正文')),
                ('excerpt', models.CharField(blank=True, max_length=200)),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author', verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='分类')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='标签')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='blog',
            name='label',
            field=models.ManyToManyField(to='blog.Label', verbose_name='标签'),
        ),
    ]
